### ISSUE TITLE
Possibility to filter result on GET request

### ISSUE THREAD

**Issue by eltojo** [navikt/pam-public-feed#11]
Possibility to pass parameters with request to filter repsonse result based on county, minicipal, city.
As of today one have to make about 50 requests to the server (limit on 100 ads pr result, set on server) to get all the ads before starting on filtering. This is rather time consuming.

**Comment by oyvindstegard** [comment]
Hei,

Takk for tilbakemelding.

Filtermuligheter er underveis. Geografi-filtrering har vi forutsett etterspørsel etter :).

**Comment by sulomann** [comment]
Hei, vil responsen inneholde samme data som filtermulighetene her https://arbeidsplassen.nav.no/stillinger? Altså at Heltid/deltid, Ansettelsesform, Sektor legges til?
Det hadde vært nyttig å kunne spørre på org.nummer i API'et også.

**Comment by oyvindstegard** [comment]
Jeg tror alle feltene du nevner er inkludert i det som vil komme med i neste prodsetting.
Vi planlegger også filtrering på geografi og yrkeskategorier.

Når det gjelder filter på org-nummer, jeg antar use-casen er å begrense til stillinger kun fra en spesifikk arbeidsgiver ? Altså "jeg vil kun hente mine egne annonser", sett fra en arbeidsgivers perspektiv ?

**Comment by sulomann** [comment]
Hei,

Use-case for å kunne spørre på org.nummer er for oss å sjekke spesifikke
bedrifter fra vår database som kan ha aktuelle stillinger for Teknas
medlemmer.

Det vil også være et case som du sier å hente for egen virksomhet til f.eks
en hjemmeside.

Mvh
Thomas Hofmann

ons. 19. jun. 2019, 16:31 skrev Øyvind Stegard <notifications@github.com>:

**Comment by livarb** [comment]
Cirka når tid blir neste prodsetjing?

**Comment by taraldr** [comment]
Status på denne?
Trenger geografisk filtrering før vi kan migrere fra https://tjenester.nav.no/stillinger/rss

**Comment by einarbj** [comment]
Det er en av de høyest prioriterte sakene våre, og er neste feature som vil implementeres i pam-public-feed. Men den er ikke påbegynt enda

**Comment by tengvig** [comment]
Dette ble prodsatt 18. september. Det er nå mulig å filtrere på orgnr, fylke og kommune (se swagger for detaljer). Det er ikke mulig å oppgi en liste med fylker eller kommuner. Ved interesse vil det sannsynligvis komme i en senere release.

**Comment by madsern** [comment]
> Dette ble prodsatt 18. september. Det er nå mulig å filtrere på orgnr, fylke og kommune (se swagger for detaljer: https://arbeidsplassen.nav.no/public-feed/swagger/ ). Det er ikke mulig å oppgi en liste med fylker eller kommuner. Ved interesse vil det sannsynligvis komme i en senere release.

Har dere fortsatt planer for å utvide filter med yrkeskategorier?

**Comment by tuantrannav** [comment]
@madsern Hei, denne issue er nå closed, fint om du kan åpne ny issue til dette. Vi tar også imot pullrequests :)
