### ISSUE TITLE
Result does not contain all active ads

### ISSUE THREAD

**Issue by eltojo** [navikt/pam-public-feed#12]
It seems to me that result contains only ads which is added in june / last 7 days. I can't be sure since it's the 7'th today :)

I have compared ads from this API to the ads from the search API:
https://arbeidsplassen.nav.no/stillinger?sort=relevant&counties[]=OPPLAND&municipals[]=OPPLAND.ETNEDAL&municipals[]=OPPLAND.NORD-AURDAL&municipals[]=OPPLAND.S%C3%98R-AURDAL&municipals[]=OPPLAND.VANG&municipals[]=OPPLAND.VESTRE%20SLIDRE&municipals[]=OPPLAND.%C3%98YSTRE%20SLIDRE

**Comment by oyvindstegard** [comment]
Hei,

Dette API-et er foreløpig begrenset til de 5000 sist publiserte annonsene. De nyeste kommer først i feeden. Og etterhvert som det strømmer inn nye vil eldre annonser gå ut av feeden. Om man jenvlig konsumerer og lagrer de sist publiserte annonsene vil man over tid bygge seg opp et mer komplett sett av alle for tiden aktive annonser, hvis det er målet. Tanken er at konsumenter som ønsker "alt" selv må mellomlagre annonsene i egne løsninger og kontinuerlig konsumere de nyeste fra feeden. UUID-felt kan brukes for å avgjøre hvilke annonser man har lagret fra før av.

Det jobbes med å få på plass filtreringsmuligheter i feeden, som gjør at man kan begrense utvalget og dermed ofte kunne komme godt under 5000. På den måten får man alle matchende aktive annonser i løpet av én page-through.

**Comment by oyvindstegard** [comment]
Det er nå mulig å hente alle annonser, gjennom en av metodene beskrevet her:
https://github.com/navikt/pam-public-feed#maximum-number-of-ads-in-feed
