### ISSUE TITLE
Resultatet henter ikke alle ads og søk på id fungerer ikke.

### ISSUE THREAD

**Issue by Wilhelm-af** [navikt/pam-public-feed#17]
Det ser ut til at søk på eldre ads funker ikke, får opp mange andre ads men ikke den jeg søkte på. (UUID jeg søkte på fdad3360-15ab-41a9-85f6-9492ce7756d2 og b014ad79-afb6-4da4-a401-801153dca6a2)

Samtidig så henter ikke resultate alle adsene
Disse er helt blanke for data. men får opp ads på side 1 og 0 samt med at det står nederst at det skal være totalt 86 Elementer og 5 sider med ads.
https://arbeidsplassen.nav.no/public-feed/api/v1/ads?page=2&published=[*,2019-01-31)
https://arbeidsplassen.nav.no/public-feed/api/v1/ads?page=3&published=[*,2019-01-31)
https://arbeidsplassen.nav.no/public-feed/api/v1/ads?page=4&published=[*,2019-01-31)

Flere som er tomme
https://arbeidsplassen.nav.no/public-feed/api/v1/ads?page=206&published=[*,2019-06-26)
https://arbeidsplassen.nav.no/public-feed/api/v1/ads?size=100&page=41&published=[*,2019-06-26)

**Comment by einarbj** [comment]
Takk for tilbakemelding. Vi er tilbake fra ferie nå, og vil begynne å se på dette

**Comment by einarbj** [comment]
De tre nedenfor skal være i orden nå. Årsaken var manglende land i noen annonser, har derfor endret det til å være nullable 

> Samtidig så henter ikke resultate alle adsene
Disse er helt blanke for data. men får opp ads på side 1 og 0 samt med at det står nederst at det skal være totalt 86 Elementer og 5 sider med ads.
https://arbeidsplassen.nav.no/public-feed/api/v1/ads?page=2&published=[*,2019-01-31)
https://arbeidsplassen.nav.no/public-feed/api/v1/ads?page=3&published=[*,2019-01-31)
https://arbeidsplassen.nav.no/public-feed/api/v1/ads?page=4&published=[*,2019-01-31)


I de nedenfor ser det ut til å være feil i spørringen, slik at man henter en side etter siste resultat. I den første hentes side (pageNumber) 206 av totalt (totalPages) 91 sider, i den siste hentes side 41 mens det totalt er 19.
> Flere som er tomme
https://arbeidsplassen.nav.no/public-feed/api/v1/ads?page=206&published=[*,2019-06-26)
https://arbeidsplassen.nav.no/public-feed/api/v1/ads?size=100&page=41&published=[*,2019-06-26)
Men innser at datagrunnlaget kan ha endret seg de siste 14 dagene, og derfor kan det ha vært feil i de når du opprettet issuen. Ta derfor kontakt hvis du opplever det samme igjen.

**Comment by einarbj** [comment]
UUIDene du nevner over ser ut til å hente annonsen. 

https://arbeidsplassen.nav.no/public-feed/api/v1/ads?uuid=fdad3360-15ab-41a9-85f6-9492ce7756d2
https://arbeidsplassen.nav.no/public-feed/api/v1/ads?uuid=b014ad79-afb6-4da4-a401-801153dca6a2

@Wilhelm-af Er det andre annonser det fortsatt er problemer å hente opp?

**Comment by Wilhelm-af** [comment]
> De tre nedenfor skal være i orden nå. Årsaken var manglende land i noen annonser, har derfor endret det til å være nullable
> 
> > Samtidig så henter ikke resultate alle adsene
> > Disse er helt blanke for data. men får opp ads på side 1 og 0 samt med at det står nederst at det skal være totalt 86 Elementer og 5 sider med ads.
> > [https://arbeidsplassen.nav.no/public-feed/api/v1/ads?page=2&published=[*,2019-01-31](https://arbeidsplassen.nav.no/public-feed/api/v1/ads?page=2&published=%5B*,2019-01-31))
> > [https://arbeidsplassen.nav.no/public-feed/api/v1/ads?page=3&published=[*,2019-01-31](https://arbeidsplassen.nav.no/public-feed/api/v1/ads?page=3&published=%5B*,2019-01-31))
> > [https://arbeidsplassen.nav.no/public-feed/api/v1/ads?page=4&published=[*,2019-01-31](https://arbeidsplassen.nav.no/public-feed/api/v1/ads?page=4&published=%5B*,2019-01-31))
> 
> I de nedenfor ser det ut til å være feil i spørringen, slik at man henter en side etter siste resultat. I den første hentes side (pageNumber) 206 av totalt (totalPages) 91 sider, i den siste hentes side 41 mens det totalt er 19.
> 
> > Flere som er tomme
> > [https://arbeidsplassen.nav.no/public-feed/api/v1/ads?page=206&published=[*,2019-06-26](https://arbeidsplassen.nav.no/public-feed/api/v1/ads?page=206&published=%5B*,2019-06-26))
> > [https://arbeidsplassen.nav.no/public-feed/api/v1/ads?size=100&page=41&published=[*,2019-06-26](https://arbeidsplassen.nav.no/public-feed/api/v1/ads?size=100&page=41&published=%5B*,2019-06-26))
> > Men innser at datagrunnlaget kan ha endret seg de siste 14 dagene, og derfor kan det ha vært feil i de når du opprettet issuen. Ta derfor kontakt hvis du opplever det samme igjen.

Får ikke fram feilen igjen så dette er sikkert fikset.

> UUIDene du nevner over ser ut til å hente annonsen.
> 
> https://arbeidsplassen.nav.no/public-feed/api/v1/ads?uuid=fdad3360-15ab-41a9-85f6-9492ce7756d2
> https://arbeidsplassen.nav.no/public-feed/api/v1/ads?uuid=b014ad79-afb6-4da4-a401-801153dca6a2
> 
> @Wilhelm-af Er det andre annonser det fortsatt er problemer å hente opp?

Men får ikke søkt på denne UUID'en
Jeg bruker PostMan til og spørre API'et for testing,
men får bare andre annonser når jeg søker på id'en
https://arbeidsplassen.nav.no/public-feed/api/v1/ads?id=fdad3360-15ab-41a9-85f6-9492ce7756d2

**Comment by Wilhelm-af** [comment]
Får heller ikke opp riktig annonse når jeg søker med https://arbeidsplassen.nav.no/public-feed/swagger/#/default/get_public_feed_api_v1_ads

**Comment by einarbj** [comment]
@Wilhelm-af Ser ut til at det er feil i dokumentasjonen/swagger. Parameteret skal hete uuid, ikke id. Oppdaterer swagger nå

**Comment by Wilhelm-af** [comment]
Da ser det ut til at alt funker! :+1:
