### ISSUE TITLE
Filter på kategori

### ISSUE THREAD

**Issue by vegardjo** [navikt/pam-public-feed#47]
Hei! 

Ser her https://github.com/navikt/pam-public-feed/issues/11 at dere la til filter for orgnr, fylke og kommune, men kan det også legges på filter for kategori / yrke? Vil trenge begge nivå, f-eks "Helse og sosial" og "Lege"

**Comment by tuantrannav** [comment]
Hei,

Takk for tilbakemelding, vi skal se på dette så fort vi får tid.

Har opprettet en task på det i backloggen.


Mvh,
Tuan.

**Comment by vegardjo** [comment]
Hei, noen videre status på dette? :)

**Comment by tuantrannav** [comment]
Denne oppgaven har blitt prioritert høyere opp nå, vi begynner på den veldig snart :)

**Comment by vegardjo** [comment]
Topp :)

**Comment by tengvig** [comment]
Vi prodsatte akkurat en mulighet for å filtrere på kategori. Dette filteret matcher begge nivå, slik at du kan søke på Helse og sosial eller Lege.

**Comment by tengvig** [comment]
Lukke issue etter prodsetting
