### ISSUE TITLE
Make municipality id available and make it possible to filter by municipality ID

### ISSUE THREAD

**Issue by livarb** [navikt/pam-public-feed#54]
Since there is currently two names of municipalities which are shared, it would be great to be able to filter by the four-digit municipality id and not only by name. It's possible to get correct results by also filtering by county, but it would be better to be able to filter by municipality id.
See which municipality-names are shared by several municipalities: https://no.wikipedia.org/wiki/Norges_kommuner#Kommunene

**Comment by tuantrannav** [comment]
Thank you for your suggestion, we dont support municipalcode. You can for example use this library to convert to the municapal names: https://github.com/navikt/pam-geography
