### ISSUE TITLE
ApplicationDue - Ulike tidsformater

### ISSUE THREAD

**Issue by JohanAanesen** [navikt/pam-public-feed#65]
ApplicationDue i "FeedAd" objektet fra [OutputPayload.kt](https://github.com/navikt/pam-public-feed/blob/master/src/main/kotlin/no/nav/pam/feed/ad/OutputPayload.kt) er definert som en string.

Stringen er enten Null, 'Snarest' eller et av følgende dato formater (som jeg har sett):
- "YYYY-MM-DDTHH:mm"
- "DD.MM.YYYY"
- "YYYY-MM-DD"
- "DD. MMMM YYYY"

Burde ikke ihvertfall dato formatene samkjøres på api nivå? Dette gjør ihvertfall api'et vanskelig å bruke når man må støtte hundre formater hvis en ønsker å 'vise' et bestemt format i sin frontend..

Forslår uansett at det dokumenters bedre hvilke verdier/formater en kan forvente returnert.

**Comment by tuantrannav** [comment]
Hei, takk for kommentaren. Feltet "expires" kan brukes for dette formålet.
