### ISSUE TITLE
CORS change?

### ISSUE THREAD

**Issue by eltojo** [navikt/pam-public-feed#76]
Hi, I can see that the latest release has removed anyHost() from CORS config: src/main/kotlin/no/nav/pam/feed/Bootstrap.kt. Are you now whitelisting instead? Since the release we can't access the endpoint to get ads.

**Comment by tuantrannav** [comment]
Hi, yes you are correct. public-feed-api was not meant to be used as a backend-api for a browser frontend.  It was only meant to be a server-server integration. Sorry for the inconvenience.
