### ISSUE TITLE
Filter mulighet på postkode

### ISSUE THREAD

**Issue by Wilhelm-af** [navikt/pam-public-feed#83]
Har utvidelse som er laget mot nav apiet. Og det fungerer bra, Men må gjøre ting dobbelt da postkode ikke har samme filter mulighet som municipal,county og orgnr. Er dette noe dere får fikset. Hadde blitt så mye likere for koden min samtidig også.

**Comment by tuantrannav** [comment]
Hei, takk for kommentaren. Vi skal legge denne på backlogg, og ser på den så fort vi får tid.
